### PR TITLE
Add Linter Github Action

### PR DESCRIPTION
**Pull request by suneettipirneni**
Runs on push to main and pull requests to main. This also reformats the code to conform to the whatever Flake8 defaults to.

### CODE REVIEW

**Comment by zenith110** [comment]
Looks good to me

**Comment by suneettipirneni** [comment]
@zenith110 does this satisfy #8 or is there something more we wanted?

**Comment by rob-3** [comment]
I'm concerned about the change in devselect.py actually changing the behavior of the code

**Comment by suneettipirneni** [comment]
> I'm concerned about the change in devselect.py actually changing the behavior of the code

Didn't spot that!, I'll revert that.

**Review by rob-3 — APPROVED** [review]

**Pull request merged**
