### PR TITLE
Add slash commands for role/skill assignment

### PR DESCRIPTION
**Pull request by suneettipirneni**
Addresses #11 

Adds slash commands:

`/addrole`, `/removerole`, `/addskill`, `/removeskill`,

Screen Shot 2021-06-14 at 10 18 33 PM

Because of slash commands it is also necessary to update you `env` to include the `GUILD_ID`.

### CODE REVIEW

**Comment by rob-3** [comment]
Looks pretty good. Consider using `add_role` and `remove_role` to be more idiomatic. Also, is there any reason you marked them as private?

**Comment by rob-3** [comment]
Oh looking more closely I guess that matches how you use the command. Still unsure of why they are marked with _ though.

**Comment by suneettipirneni** [comment]
> Oh looking more closely I guess that matches how you use the command. Still unsure of why they are marked with _ though.

I've changed the names to snake case, and removed the leading underscores. I've also made the message ephemeral.

**Review by rob-3 — APPROVED** [review]
I've yet to test but seems good. My production requirements aren't very high since no one is using the bot rn. Approved.

**Pull request merged**
